name: contribution_heatmap_playground
description: "Play ground for contribution_heatmap package to try before using it in your project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  contribution_heatmap:
    path: ../
  syntax_highlight: ^0.5.0

flutter:
  uses-material-design: true